#!/bin/bash

NAME=$1

if [ -z "$NAME" ]; then
    NAME="default"
fi

# Set machine ip
read -p "Enter ip: " newip

if [ -z "$newip" ]; then
    newip="192.168.99.100"
fi

docker-machine ssh $NAME \
    'sudo sh -s' \
    -- < machine-init \
    $HOME $newip

echo '==> Restart and regenerate certs'
docker-machine restart $NAME
docker-machine regenerate-certs -f $NAME

