#!/bin/bash

NAME=$1

if [ -z "$NAME" ]; then
    NAME="default"
fi

# Set machine ip
read -p "Enter ip: " newip

if [ -z "$newip" ]; then
    newip="192.168.99.100"
fi

# Initialize docker machine
docker-machine ssh $NAME \
    'sudo sh -s' \
    -- < machine-init \
    $HOME $newip

# Restart and regenerate certs
echo "==> Restart $NAME ..."
docker-machine restart $NAME

echo "==> Regenerate certs ..."
docker-machine regenerate-certs -f $NAME

